KTB-07-word-learning
kotatka/KotlinTelegramBot pull request #5
Opened 2024-11-04 10:35 UTC by kotatka

2024-11-04 17:32 UTC, dzenonce requested changes

2024-11-04 17:32 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +                    val correctAnswer = questionWords.random()
Давай возьмем `questionWords` и с помощью `mapIndexed {}` и `joinToString` получим строку с вариантами ответа.

2024-11-04 17:32 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +                    val questionWords = notLearnedList.take(4).shuffled()
Ты делаешь сначала `take`, и только потом `shuffled()` - это может вызывать проблемы.

2024-11-05 16:19 UTC, dzenonce requested changes
Уже хорошо, но давай еще немного улучшим

2024-11-05 16:19 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +                    val answerOptions = questionWords.mapIndexed { index, word -> "${index + 1} - ${word.translate}\n" }
Давай в `joinToString` используем: параметр `separator` для переноса строки, `prefix` непосредственно для оригинального слова на английском, а  `postfix` переносы строки и пункт меню для выхода.
И в println() будем выводить `answerOptions`
Тогда будет еще аккуратнее выглядеть)

2024-11-07 04:58 UTC, danelyan approved these changes

2024-11-07 08:21 UTC, merged